@startuml
participant "Autor (synchron)" as autor
participant "Sender (synchron)" as sender  #LightGreen

activate autor

autor -> sender: checkAccountActive
note right 
muss zu einem beliebigen 
Zeitpunkt aufgerufen werden
end note
activate sender
return

autor -> sender: lookupService
note right 
muss zu einem beliebigen 
Zeitpunkt aufgerufen werden
end note
activate sender
return

autor -> sender: createMessageID
activate sender
return

autor -> sender: sendMessageSync
note right
muss nach createMessageID 
aufgerufen werden
end note
activate sender
return

autor -> sender: getTransportReport
note right
muss nach sendMessageSync
aufgerufen werden
end note
activate sender
return
@enduml